In [ ]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees) if employees else 0

    def __str__(self):
        return f"Employee(name={self.name}, family={self.family}, salary={self.salary}, department={self.department})"

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)
        # attributes  to FulltimeEmployee can be added here

    def __str__(self):
        return f"FulltimeEmployee(name={self.name}, family={self.family}, salary={self.salary}, department={self.department})"

# Creating instances of Employee
emp1 = Employee("Sai", "Jayavarapu", 60000, "HR")
emp2 = Employee("Yash", "Seelam", 70000, "Finance")

# Creating instances of FulltimeEmployee
ft_emp1 = FulltimeEmployee("Jagga", "CH", 80000, "IT")
ft_emp2 = FulltimeEmployee("Satish", "Kilaru", 75000, "Marketing")

# List of all employees
all_employees = [emp1, emp2, ft_emp1, ft_emp2]

# Calculate and print average salary(average of salary of all employees)
employee = Employee("Temp", "Temp", 0, "None")
print(f"Average Salary: {employee.average_salary(all_employees)}")

# Print the details of each employee
for emp in all_employees:
    print(emp)

# Print total number of employees
print(f"Total number of employees: {Employee.employee_count}")


Average Salary: 71250.0
Employee(name=Sai, family=Jayavarapu, salary=60000, department=HR)
Employee(name=Yash, family=Seelam, salary=70000, department=Finance)
FulltimeEmployee(name=Jagga, family=CH, salary=80000, department=IT)
FulltimeEmployee(name=Satish, family=Kilaru, salary=75000, department=Marketing)
Total number of employees: 5


Employee Class:
-----------------------

Class Variable: employee_count is used to keep track of the number of Employee instances.

Constructor: Initializes the attributes and increments the employee count.


Method average_salary: Computes the average salary given a list of
Employee instances.

__str__ Method: Provides a string representation for easier printing.


FulltimeEmployee Class:
---------------------------------

Inherits from Employee and can be extended with more attributes or methods if needed.

__str__ Method: Provides a specific string representation for FulltimeEmployee.

Creating Instances and Calling Methods:
-----------------------------------------------------

Instances of both Employee and FulltimeEmployee are created and added to a list.


The average_salary method calculates the average salary of all employees.

Details of each employee are printed along with the total count.

In [ ]:
import numpy as np

#random vector of size 20 with floats in the range 1-20
vector = np.random.uniform(1, 20, size=20)
print(vector)
print()

#vector to 4x5
matrix = vector.reshape(4, 5)

#Replace the max in each row with 0 (axis=1)
# Get the indices of the maximum values along axis=1
max_indices = np.argmax(matrix, axis=1)

# Create a boolean mask where the max values are True
mask = np.arange(matrix.shape[1]) == max_indices[:, None]

# Apply the mask to set max values to 0
matrix[mask] = 0

# Output the result
print("Matrix after replacing max values with 0:")
print(matrix)


[14.71042326 15.92696988  6.52449954  6.96964416  7.17893182  1.32979397
  7.54668183  9.20870586  2.04642508  4.52507593 12.61190622 13.27097701
 11.79929854 14.47961261 12.04396595  9.7939467  18.9614108  10.19713333
  6.57343322  1.23961343]

Matrix after replacing max values with 0:
[[14.71042326  0.          6.52449954  6.96964416  7.17893182]
 [ 1.32979397  7.54668183  0.          2.04642508  4.52507593]
 [12.61190622 13.27097701 11.79929854  0.         12.04396595]
 [ 9.7939467   0.         10.19713333  6.57343322  1.23961343]]


np.random.uniform(1, 20, size=20) generates 20 random float values uniformly distributed between 1 and 20

reshape(4, 5) converts the vector into a 4x5 matrix

np.argmax(matrix, axis=1) returns the indices of the maximum values in each row

np.arange(matrix.shape[1]) creates an array of column indices

max_indices[:, None] reshapes max_indices to be a column vector

mask is a 2D boolean array where True indicates the position of the maximum valuesand then use boolean indexing to set the maximum values to zero